# Generated by Django 5.2.7 on 2025-11-02 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='paid_courses',
            new_name='paid_course',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='paid_lessons',
            new_name='paid_lesson',
        ),
    ]
