# Generated by Django 5.2.7 on 2025-11-22 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_alter_lesson_course'),
        ('lms', '0004_coursesubscription'),
    ]

    operations = [
    ]
